Read fichier csv de webscriping

In [1]:
import pandas as pd

df=pd.read_csv('books.csv')
df.head()

,Titre,Prix,Rating,Stock,Description
0,A Light in the Attic,£51.77,3,22,It's hard to imagine a world without A Light i...
1,Tipping the Velvet,£53.74,1,20,"""Erotic and absorbing...Written with starling ..."
2,Soumission,£50.10,1,20,"Dans une France assez proche de la nôtre, un h..."
3,Sharp Objects,£47.82,4,20,"WICKED above her hipbone, GIRL across her hear..."
4,Sapiens: A Brief History of Humankind,£54.23,5,20,From a renowned historian comes a groundbreaki...

Affichier last 10

In [2]:
df.tail(10)

,Titre,Prix,Rating,Stock,Description
990,Bridget Jones's Diary (Bridget Jones #1),£29.82,1,1,Meet Bridget Jones—a 30-something Singleton wh...
991,Bounty (Colorado Mountain #7),£37.26,4,1,Justice Lonesome has enjoyed a life of bounty....
992,Blood Defense (Samantha Brinkman #1),£20.30,3,1,First in a new series from bestselling author ...
993,"Bleach, Vol. 1: Strawberry and the Soul Reaper...",£34.65,5,1,"Hot-tempered 15-year-old Ichigo Kurosaki, the ..."
994,Beyond Good and Evil,£43.38,1,1,Friedrich Nietzsche's Beyond Good and Evil is ...
995,Alice in Wonderland (Alice's Adventures in Won...,£55.53,1,1,No description available
996,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",£57.06,4,1,High school student Kei Nagai is struck dead i...
997,A Spy's Devotion (The Regency Spies of London #1),£16.97,5,1,"In England’s Regency era, manners and elegance..."
998,1st to Die (Women's Murder Club #1),£53.98,1,1,"James Patterson, bestselling author of the Ale..."
999,"1,000 Places to See Before You Die",£26.08,5,1,"Around the World, continent by continent, here..."