In [3]:
import pandas as pd
df=pd.read_csv(r'C:\Users\saido\Desktop\ApplicationGestionAi\CreationModelAi\ModelAi\livres_bruts.csv')
df.head()

,title,description,price,availability,image_url,rating
0,A Light in the Attic,It's hard to imagine a world without A Light i...,£51.77,In stock,https://books.toscrape.com/media/cache/2c/da/2...,star-rating Three
1,Tipping the Velvet,"""Erotic and absorbing...Written with starling ...",£53.74,In stock,https://books.toscrape.com/media/cache/26/0c/2...,star-rating One
2,Soumission,"Dans une France assez proche de la nôtre, un h...",£50.10,In stock,https://books.toscrape.com/media/cache/3e/ef/3...,star-rating One
3,Sharp Objects,"WICKED above her hipbone, GIRL across her hear...",£47.82,In stock,https://books.toscrape.com/media/cache/32/51/3...,star-rating Four
4,Sapiens: A Brief History of Humankind,From a renowned historian comes a groundbreaki...,£54.23,In stock,https://books.toscrape.com/media/cache/be/a5/b...,star-rating Five

In [4]:
df2=pd.read_csv(r'C:\Users\saido\Desktop\ApplicationGestionAi\CreationModelAi\ModelAi\livres_nettoyes.csv')
df2.head()

,title,description,price,availability,image_url,rating
0,A Light in the Attic,It s hard to imagine a world without A Light i...,51.77,0,https://books.toscrape.com/media/cache/2c/da/2...,3
1,Tipping the Velvet,Erotic and absorbing Written with starling pow...,53.74,0,https://books.toscrape.com/media/cache/26/0c/2...,1
2,Soumission,Dans une France assez proche de la n tre un ho...,50.10,0,https://books.toscrape.com/media/cache/3e/ef/3...,1
3,Sharp Objects,WICKED above her hipbone GIRL across her heart...,47.82,0,https://books.toscrape.com/media/cache/32/51/3...,4
4,Sapiens: A Brief History of Humankind,From a renowned historian comes a groundbreaki...,54.23,0,https://books.toscrape.com/media/cache/be/a5/b...,5

In [5]:
df2.tail(10)

,title,description,price,availability,image_url,rating
290,Looking for Lovely: Collecting the Moments tha...,I want you to take every step of your life wit...,29.14,0,https://books.toscrape.com/media/cache/61/1e/6...,5
291,Living Leadership by Insight: A Good Leader Ac...,Learning not shared is learning wasted In my t...,46.91,0,https://books.toscrape.com/media/cache/e9/5e/e...,4
292,Let It Out: A Journey Through Journaling,You want change Maybe your career isn t what y...,26.79,0,https://books.toscrape.com/media/cache/51/fc/5...,5
293,Lady Midnight (The Dark Artifices #1),In a kingdom by the sea In a secret world wher...,16.28,0,https://books.toscrape.com/media/cache/89/a6/8...,5
294,"It's All Easy: Healthy, Delicious Weeknight Me...",For fans of It s All Good or just delicious fo...,19.55,0,https://books.toscrape.com/media/cache/fe/67/f...,1
295,Island of Dragons (Unwanteds #7),Twins Alex and Aaron Stowe are put to the ulti...,29.65,0,https://books.toscrape.com/media/cache/75/b9/7...,1
296,I Know What I'm Doing -- and Other Lies I Tell...,New York Times bestselling author and stand up...,25.98,0,https://books.toscrape.com/media/cache/ea/7b/e...,4
297,I Am Pilgrim (Pilgrim #1),A breakneck race against time and an implacabl...,10.60,0,https://books.toscrape.com/media/cache/ed/07/e...,4
298,"Hyperbole and a Half: Unfortunate Situations, ...",This is a book I wrote Because I wrote it I ha...,14.75,0,https://books.toscrape.com/media/cache/b5/a9/b...,5
299,"Hush, Hush (Hush, Hush #1)",A SACRED OATHA FALLEN ANGELA FORBIDDEN LOVERom...,47.02,0,https://books.toscrape.com/media/cache/2a/b9/2...,3